# Generated by Django 5.2.3 on 2025-08-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedido_pagamento_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('apple', 'Apple'), ('xbox', 'Xbox'), ('playstation', 'Playstation'), ('relogio', 'Relogios'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria'),
        ),
    ]
