# Generated by Django 5.2.3 on 2025-08-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_produto_descricao_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('apple', 'Apple'), ('xbox', 'Xbox'), ('playstation', 'Playstation'), ('relogio', 'Relogios'), ('macbook', 'Macbook'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria'),
        ),
    ]
