# Generated by Django 5.2 on 2025-09-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_formapagamento_delete_tipopagamento_and_more'),
    ]

    operations = [
    ]
