# Generated by Django 5.2 on 2025-09-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_adicionar_produto_ativo'),
    ]

    operations = [
    ]
