# Generated by Django 5.2 on 2025-09-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20250913_0342'),
    ]

    operations = [
    ]
