# Generated by Django 5.2 on 2025-09-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20250913_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='status',
            field=models.CharField(
                max_length=20,
                choices=[('aberto','Aberto'),('finalizado','Finalizado')],
                default='aberto'
            ),
        ),
    ]