# Generated by Django 5.2.3 on 2025-09-15 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20250913_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.cliente'),
        ),
    ]
