# Generated by Django 5.2.8 on 2026-04-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_pagamento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('apple', 'Apple'), ('xbox', 'Xbox'), ('playstation', 'Playstation'), ('relogio', 'Relógios'), ('macbook', 'Macbook'), ('fones', 'Fones'), ('gamer', 'Gamer'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
